[2018-08-08 19:18:21,227] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from '/home/rcw/project/DjangoBlog/comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from '/home/rcw/project/DjangoBlog/servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'static/CACHE/css/2490f7c132d2.css'}
[2018-08-08 19:18:21,229] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from '/home/rcw/project/DjangoBlog/comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from '/home/rcw/project/DjangoBlog/servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'static/CACHE/css/e7c1c03fad03.css'}
[2018-08-08 19:18:21,231] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from '/home/rcw/project/DjangoBlog/comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from '/home/rcw/project/DjangoBlog/servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'static/CACHE/js/c71e77581f2f.js'}
[2018-08-08 19:18:24,497] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from '/home/rcw/project/DjangoBlog/blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from '/home/rcw/project/DjangoBlog/comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/rcw/project/DjangoBlog/accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from '/home/rcw/project/DjangoBlog/oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from '/home/rcw/project/DjangoBlog/servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from '/home/rcw/project/DjangoBlog/owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'favicon.ico'}
[2018-08-08 19:28:41,871] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'favicon.ico'}
[2018-08-08 19:35:40,486] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'favicon.ico'}
[2018-08-08 19:35:49,283] ERROR [blog.views.page_not_found_view:279 views] {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]], 'path': 'favicon.ico'}
[2018-08-08 19:40:22,017] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 19:40:22,018] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 19:52:05,905] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 19:52:19,247] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 19:52:19,247] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 19:54:25,119] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 19:54:25,153] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 19:54:50,151] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 19:54:50,151] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 20:04:22,979] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 20:04:30,469] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 20:04:30,469] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 20:16:57,040] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 20:16:57,062] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-08 20:17:14,813] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-08 20:17:14,814] ERROR [blog.templatetags.blog_tags.datetimeformat:55 blog_tags] 'NoneType' object has no attribute 'strftime'
[2018-08-11 09:50:06,243] ERROR [blog.views.page_not_found_view:279 views] {'path': 'admin/css/base.css', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern '' [name='index']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'jsi18n/' [name='jsi18n']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'r/<int:content_type_id>/<path:object_id>/' [name='view_on_site']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/blogsettings/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/links/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/article/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'servermanager/commands/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/sidebar/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'accounts/bloguser/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'sites/site/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'oauth/oauthconfig/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'servermanager/emailsendlog/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'admin/logentry/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'owntracks/owntracklog/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/category/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'comments/comment/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'oauth/oauthuser/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/tag/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern '^(?P<app_label>blog|servermanager|accounts|sites|oauth|admin|owntracks|comments)/$' [name='app_list']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:50:06,305] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'admin/css/base.css', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern '' [name='index']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'login/' [name='login']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'logout/' [name='logout']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'password_change/' [name='password_change']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'password_change/done/' [name='password_change_done']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'jsi18n/' [name='jsi18n']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern 'r/<int:content_type_id>/<path:object_id>/' [name='view_on_site']>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/blogsettings/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/links/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/article/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'servermanager/commands/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/sidebar/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'accounts/bloguser/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'sites/site/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'oauth/oauthconfig/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'servermanager/emailsendlog/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'admin/logentry/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'owntracks/owntracklog/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/category/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'comments/comment/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'oauth/oauthuser/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLResolver <URLPattern list> (None:None) 'blog/tag/'>], [<URLResolver <URLPattern list> (admin:admin) '^admin/'>, <URLPattern '^(?P<app_label>blog|servermanager|accounts|sites|oauth|admin|owntracks|comments)/$' [name='app_list']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:50:14,916] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/article_index.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:21,649] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/article_index.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:22,891] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/article_index.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:25,565] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/article_index.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:35,943] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/article_index.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:35,945] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:51:35,980] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:45,193] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:51:45,208] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:51:50,216] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:51:50,228] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:52:02,170] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:52:02,182] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:52:03,018] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:52:03,031] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
[2018-08-11 09:52:24,248] ERROR [blog.views.page_not_found_view:279 views] {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}
[2018-08-11 09:52:24,260] WARNING [django.template.render:210 loader_tags] Exception raised while rendering {% include %} for template 'blog/error_page.html'. Empty string rendered instead.
Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<URLResolver <URLPattern list> (admin:admin) '^admin/'>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern '' [name='index']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'page/<int:page>/' [name='index_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html' [name='detailbyid']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>.html' [name='category_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'category/<slug:category_name>/<int:page>.html' [name='category_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>.html' [name='author_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'author/<author_name>/<int:page>.html' [name='author_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>.html' [name='tag_detail']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'tag/<slug:tag_name>/<int:page>).html' [name='tag_detail_page']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'archives.html' [name='archives']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'upload' [name='upload']>], [<URLResolver <module 'blog.urls' from './blog/urls.py'> (blog:blog) ''>, <URLPattern 'refresh' [name='refresh']>], [<URLResolver <module 'comments.urls' from './comments/urls.py'> (comments:comment) ''>, <URLPattern 'article/<int:article_id>/postcomment' [name='postcomment']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^login/$' [name='login']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^register/$' [name='register']>], [<URLResolver <module 'accounts.urls' from './accounts/urls.py'> (accounts:account) ''>, <URLPattern '^logout/$' [name='logout']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/authorize'>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/requireemail/<int:oauthid>.html' [name='require_email']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/emailconfirm/<int:id>/<sign>.html' [name='email_confirm']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/bindsuccess/<int:oauthid>.html' [name='bindsuccess']>], [<URLResolver <module 'oauth.urls' from './oauth/urls.py'> (oauth:oauth) ''>, <URLPattern 'oauth/oauthlogin' [name='oauthlogin']>], [<URLPattern '^sitemap\.xml$' [name='django.contrib.sitemaps.views.sitemap']>], [<URLPattern '^feed/$'>], [<URLResolver <module 'haystack.urls' from '/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/haystack/urls.py'> (None:None) '^search'>], [<URLResolver <module 'servermanager.urls' from './servermanager/urls.py'> (servermanager:servermanager) ''>, <URLPattern 'robot'>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/logtracks' [name='logtracks']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_maps' [name='show_maps']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/get_datas' [name='get_datas']>], [<URLResolver <module 'owntracks.urls' from './owntracks/urls.py'> (owntracks:owntracks) ''>, <URLPattern 'owntracks/show_dates' [name='show_dates']>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 313, in render
    if match:
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 276, in __bool__
    self._fetch_all()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rcw/.virtualenvs/Python3/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'blog_article.slug' in 'field list'")
